### ISSUE TITLE
New Nitter Changes

### ISSUE THREAD

**Issue by muenze8** [bocchilorenzo/ntscraper#10]
Hello

Apparently X deployed some changes the last few days that broke Nitter again, and then Nitter just deployed changes from their side and the service is back up. However, ntscraper now simply stops after 5 fetches from nitter and that's it.

`19-Aug-23 13:43:39 - Error fetching https://nitter.net, trying another random instance
19-Aug-23 13:43:40 - Error fetching https://nitter.net, trying another random instance
19-Aug-23 13:43:42 - Error fetching https://nitter.net, trying another random instance
19-Aug-23 13:43:43 - Error fetching https://nitter.net, trying another random instance
19-Aug-23 13:43:44 - Error fetching https://nitter.net, trying another random instance
19-Aug-23 13:43:45 - Max retries reached. Check your request and try again`

**Comment by psegovias** [comment]
I think we should wait for nitter to publish the new version

**Comment by psegovias** [comment]
update: i just try the new update of nitter with the current version of ntscraper and work fine.

**Comment by sirrth** [comment]
when i calling the get_tweets function :

`raw_data = scraper.get_tweets("papua", number=5, max_retries=20`

somehow the random instances doesnt work and returning error like this :

> 23-Aug-23 15:43:48 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:43:50 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:43:52 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:43:55 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:43:57 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:43:59 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:01 - https://nitter.net/ unreachable, trying another random instance
23-Aug-23 15:44:03 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:05 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:07 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:10 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:13 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:15 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:17 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:19 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:22 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:24 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:26 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:28 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:31 - Error fetching https://nitter.net/, trying another random instance
23-Aug-23 15:44:32 - Max retries reached. Check your request and try again.

**Comment by bocchilorenzo** [comment]
Thank you, fixed with the last commit. Apparently the instances page has a slightly different table layout. To get the fix just update the library.

**Comment by muenze8** [comment]
> Thank you, fixed with the last commit. Apparently the instances page has a slightly different table layout. To get the fix just update the library.

Apparently the issue still persists, even after updating the library.

**Comment by bocchilorenzo** [comment]
I just pushed a small fix for the video urls in regular tweets, but I'm unable to reproduce the original issue you're having. Some instances don't work correctly, but for example the nitter.privacydev.net and nitter.cz instances work without issues.

**Comment by muenze8** [comment]
> 

The below is a snippet of what I am doing, even specifying an instance still produces the same error. If I put the exacy query directly on Nitter's UI, it works well. The error is below the code snippet for your referece.

`#manual run to bring unarchived tweets
else:
    print('Manual Run \n')
    runTime = datetime.datetime.now(datetime.timezone.utc)
    
    newTweets = []
    insertedTweets = []
    tweetsList = []
    
    #get all tweets matching the search condition
    
    while True:
        try:
            tweets = nitter.get_tweets(termsManual, 
                                       'term', 
                                       since=manualDateSince, 
                                       until=manualDateUntil, 
                                       max_retries=20, 
                                       instance="https://nitter.privacydev.net")
            
        except IndexError: #user has no tweets in the specified time range, just skip this error
            continue
        except Exception as error:
            print("An exception occurred:", type(error).__name__)        
            continue
        break
    
    if tweets is not None:
        newTweets = newTweets + tweets['tweets']
        for tweet in tweets['threads']:
            newTweets.append(tweet)`

`25-Aug-23 18:57:47 - Empty profile on https://nitter.privacydev.net, trying another random instance
25-Aug-23 18:57:49 - Empty profile on https://nitter:nitter@nitter.nixnet.services, trying another random instance
25-Aug-23 18:57:50 - Empty profile on https://nitter.privacydev.net, trying another random instance
25-Aug-23 18:57:51 - Error fetching https://nitter.net, trying https://nitter.net
25-Aug-23 18:57:52 - Error fetching https://nitter.net, trying https://nitter.privacydev.net
25-Aug-23 18:57:54 - Empty profile on https://nitter.privacydev.net, trying another random instance
.........
.........`

**Comment by bocchilorenzo** [comment]
I've added a "cooldown" system that temporarily pauses the current instance for 20 seconds if it has issues and also made the sleep between calls 2 seconds instead of 1 (it seemed more stable when testing it). Please update the library and try it out, currently it gives me no issues with the same code you provided.

**Comment by muenze8** [comment]
> I've added a "cooldown" system that temporarily pauses the current instance for 20 seconds if it has issues and also made the sleep between calls 2 seconds instead of 1 (it seemed more stable when testing it). Please update the library and try it out, currently it gives me no issues with the same code you provided.

Done, just updated and ran the script again. From the initial run, it seems to be solved. Let's see how it goes as days pass. Hopefully the tesla guy stops forcing changes too.

**Comment by muenze8** [comment]
@bocchilorenzo there is another issue now. It loops through the "Max retries reached" error and never goes out.

**Comment by bocchilorenzo** [comment]
Should be fixed now with the latest commit
